# Plugins
gems:
- jekyll-sitemap
safe: false

# Build Settings
markdown: kramdown
permalink: pretty
exclude: ['/automation/', 'README.md', 'LICENSE.txt', 'CNAME']


# Site Settings
title: "Blumenau Dev Day 2023"
email: "hackerspaceblumenau@gmail.com"
description: "Evento para reunir todas as comunidades de Blumenau SC"
baseurl: "/blumenau-dev-day"
url: "https://hackerspaceblumenau.org"
permalink: "/blog/:title"
googleAnalyticsTrackingId: "UA-91819658-1"
googleAnalyticsSiteUrl: "https://www.hackerspaceblumenau.org/"
siteVerification: "d8bf6da5-4361-467a-a782-eab138c47b60"
googleAPIKey: "AIzaSyDcQf1AqXxyAzbWhsTtKJ09uerJuAygA4Y"

# Organizer Info
organizerName: "Hackerspace Blumenau"
organizerAlternateName: "Hackerspace Blumenau"
organizerDescription: "O Hackerspace Blumenau visa ser um espaço comunitário, aberto e colaborativo com disponibilização de uma infraestrutura para realização de encontros, eventos, oficinas e projetos em diversas áreas relacionadas a tecnologia, visando sempre a troca de conhecimento."
organizerEmail: "hackerspaceblumenau@gmail.com"
organizerLogo: "/img/organizers/hackerspaceblumenau.png"
organizerLink: "https://www.hackerspaceblumenau.org/"

# Head
metaKeywords: "Blumenau, dev, programming, developers"
twitterAccount: "@hackerspacebnu"
socialImageSrcGooglePlus: "/img/organizers/BlumenauDevDay.png"
socialImageSrcTwitter: "/img/organizers/BlumenauDevDay.png"
socialImageSrcFacebook: "/img/organizers/BlumenauDevDay.png"

# Documents
# c4pUrl: "https://forms.gle/Tf6v4FQJJyN369Gj9"
# c4sponsorsUrl: "/assets/GDG_DevFest_Partnership.pdf"


# Navigation
navigationLinks:
 - {permalink: "/", text: "Home"}
 - {permalink: "/blog/", text: "Blog"}
 - {permalink: "/programacao/", text: "Programação"}
 - {permalink: "/speakers/", text: "Speakers"}
 - {permalink: "/team/", text: "Organizadores"}
 - {permalink: "/assets/BLUMENAU-DEV-DAY-2023-Media-Kit.pdf", text: "Media Kit 2023"}
 - {permalink: "/2019/", text: "Veja como foi em 2019"}
 # - {link: "https://photos.app.goo.gl/WBX33VGoVfMip7mS6", text: "Fotos do evento"}
 - {link: "https://www.sympla.com.br/evento/blumenau-dev-day-2023/2230874", text: "Faça a sua inscrição"}
# - {permalink: "/logistics/", text: "Logistics"}
# - {permalink: "/hackathon/", text: "Hackathon"}
bottomNavigationLinks:
  - {link: "https://www.sympla.com.br/evento/blumenau-dev-day-2023/2230874", text: "Faça a sua inscrição"}
rightNavigationButtons:
  - {link: "https://www.sympla.com.br/evento/blumenau-dev-day-2023/2230874", text: "Faça a sua inscrição"}

# Hero Block
heroImage: "hero.jpg"
heroTitle: "Blumenau Dev Day <typeout>"
eventDate: "9 de Dezembro 2023"
typeoutTextValues: '"", "DotNetCoders", "GruPy", "Hackerspace Blumenau", "Elastic Blumenau User Group"'
typeoutFallback: ""
heroButtons:
  - {link: "https://www.sympla.com.br/evento/blumenau-dev-day-2023/2230874", text: "Faça a sua inscrição"}
  # - {permalink: "/#tickets", text: "Buy tickets"}

# About Block
aboutTitle: "Sobre Blumenau Dev Day"
aboutBlock:
 - {title: "Palestras", image: "conference.jpg", text: "Palestras sobre linguagens, frameworks, metodologias e muito mais." }
 - {title: "Lightning Talks", image: "lightningtalks.png", text: "Lightning Talks, palestras mais rápidas sobre tecnologia e agile." }
 - {title: "Comunidades", image: "workshop.jpg", text: "Todas as comunidades de Blumenau reunidas para promover networking e conhecimento." }

# Statistic Block
statisticBlockImage: "statistic.jpg"
statisticBlock:
# - {count: "350", specialCharacter: "+", info: "attendees", detail: "from everywhere"}
 - {count: "8", specialCharacter: "+", info: "horas", detail: "de palestras e conteúdo"}
 - {count: "9", specialCharacter: "+", info: "palestrantes", detail: "de Blumenau e além"}
 - {count: "9", specialCharacter: "", info: "comunidades", detail: "da região"}

# Latest News Block
latestNewsTitle: "Últimas novidades"

# Rockstar Speakers Block
rockstarSpeakersImage: "rockstar-speakers.jpg"
rockstarSpeakersCount: 4
rockstarSpeakersTitle: "Rockstar speakers"
rockstarSpeakersButtonText: "Veja todos os palestrantes"

# Location Block
locationBlockTitle: "Presncial"
eventLocationName: ""
eventLocationLink: "#"
eventStreetAddress: ""
eventAddressLocality: ""
eventAddressLocalityRegion: "Blumenau"
eventPostalCode: ""
eventAddressCountry: "Brasil"
eventStartTime: "2023-12-09T10:00"
eventDoorTime: "10:00"
eventEndTime: "2023-12-09T20:00"
eventPlaceCoordinates: "-26.905613, -49.078779"
mapCenterCoordinates: "-26.905613, -49.078779"
mapMobileCenterCoordinates: "-26.905613, -49.078779"

# Venue Block
venueBlockTitle: "Venue"
venueBigImage: "venue_0.jpg"
venueSmallImage1: "venue_1.jpg"
venueSmallImage2: "venue_2.jpg"
venueSmallImage3: "venue_3.jpg"
venueTitle: "Kinopalace Cinema"
venueFeatures: ["3 huge cinema screens", "Doulby Digital Surround EX audio system", "Located directly in the city center"]

# Tweets Feed Block
tweetsFeedImage: "twitter-feed.jpg"
tweetsFeedTitle: "Fique por dentro"
twitterHashTag: "blumenaudevday"
twitterFeed: "https://twitter.com/search?q=%23blumenaudevday&src=typed_query"

# Partners Block
organizersTitle: "Organizadores"
partnersTitle: "Parceiros"
partnersC4sponsorsButton: "Apoie este evento"
c4sponsorsUrl: "/assets/BLUMENAU-DEV-DAY-2023-Media-Kit.pdf"

# Subscribe Block
subscribeImage: "subscribe.jpg"
subscribeTitle: "Fique por dentro!"
subscribeAction: "mailto:hackerspaceblumenau@gmail.com"
subscribeInfo: "As inscrições estarão abertas no final de Novembro. O número de ingressos é limitado. Fique ligado"

# Tickets Block
ticketsTitle: "Pricetable"
ticketsInfo: "Tickets grant access to all conference sections, coffee brakes, lunch and party. Accommodation is NOT included in the ticket price."
ticketsOffers:
 -
  name: "Early Bird"
  price: "350"
  priceCurrency: "UAH"
  ticketsNumber: "150"
  ribbon: "-5%"
  buyButtonLink: "http://dfua.ticketforevent.com/"
  buyButtonText: "Buy Now"
  ticketContentList: ["Lorem ipsum is simply", "Dummy text of the printing", "Typesetting industry"]
  validFrom: "2014-08-25T10:00"
  validThrough: "2014-09-30T23:59"
 -
  name: "Last Chance"
  price: "450"
  priceCurrency: "UAH"
  ticketsNumber: "100"
  ribbon: "-20%"
  featured: true
  buyButtonLink: "http://dfua.ticketforevent.com/"
  buyButtonText: "Buy Now"
  ticketContentList: ["Lorem ipsum is simply", "Dummy text of the printing", "Typesetting industry"]
  validFrom: "2014-10-01T00:00"
  validThrough: "2014-10-23T23:59"
  disabled: true
 -
  name: "Student"
  price: "200"
  priceCurrency: "UAH"
  ticketsNumber: "50"
  buyButtonLink: "http://dfua.ticketforevent.com/"
  buyButtonText: "Buy Now"
  additionalInfo: "Requires a valid student ID at the conference check in. Without student ID at the check in, ticket will be cancelled without refund"
  ticketContentList: ["Lorem ipsum is simply", "Dummy text of the printing", "Typesetting industry"]
  validFrom: "2014-08-20T10:00"
  validThrough: "2014-10-23T23:59"
  soldOut: true
  soldOutText: "Sold Out"

# Footer
socialLinks:
 - {link: "https://hackerspaceblumenau.slack.com/", icon: "slack"}
 - {link: "https://twitter.com/hackerspacebnu", icon: "twitter"}
 - {link: "https://facebook.com/hackerspace.blumenau", icon: "facebook"}
 - {permalink: "/feed.xml", icon: "rss"}
footerBlocks:
 -
  title: "Links"
  links:
   - {link: "https://www.hackerspaceblumenau.org", text: "Hackerspace Blumenau"}
 -
  title: "Contatos"
  links:
   - {link: "mailto:hackerspaceblumenau@gmail.com", text: "por email"}
 -
  title: "Apoioadores"
  links:
    #  - {permalink: "/cod/", text: "Code of Conduct"}
    - {permalink: "/assets/BLUMENAU-DEV-DAY-2023-Media-Kit.pdf", text: "Media Kit 2023"}
#  -
#   title: "FAQ"
#   links:
    #  - {permalink: "/cod/", text: "Code of Conduct"}

# Blog
blogTitle: "Últimas novidades"
blogCommentsEnabled: true
discusShortName: "blumenaudevday"

# Speakers List Block
showSessions: true

# Team Block
teamBlockTitle: "Sobre nós"
aboutUs: "O Hackerspace Blumenau visa ser um espaço comunitário, aberto e colaborativo com disponibilização de uma infraestrutura para realização de encontros, eventos, oficinas e projetos em diversas áreas relacionadas a tecnologia, visando sempre a troca de conhecimento. O espaço é aberto a comunidade, sendo assim todos podem participar."

# Logistics Find Way Block
findWayTitle: "Find your way here"
findWayDistance: "Distance"
findWayDriving: "DRIVING"
findWayWalking: "WALKING"
findWayBicycling: "BICYCLING"
findWayTransit: "TRANSIT"
findWayFindFlight: "Find Flight"
logisticsMapCenterCoordinates: "49.056728, 3.117289"
logisticsMapMobileCenterCoordinates: "48.335365, 23.711648"
logisticsMapAutoDirections: false

# Logistics Direction Details Block
directionDetailsImage: "direction-details.jpg"
directionDetailsTitle: "Get around Lviv"
directionDetailsCards:
 - {title: "From the Airport", information: 'Airport is right at the city border. It is easily reachable by car, public transport or taxi. More information is available at <a href="http://lwo.aero/en/transport">airport website</a>.'}
 - {title: "Public Transit", information: 'Google Transit is available in Lviv. So you can find your way in Google Maps. Moreover, you can download any of the offline public transit apps available for Lviv.'}
 - {title: "Hotels", information: 'Lviv has lots of great hotels and hostels. More information will be available later.'}
directionDetailsWideCards:
 -
  title: "Questions?"
  subCards:
   -
    title: "Hotels"
    links:
     - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}
   -
    title: "Registration"
    links:
     - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}
   -
    title: "Attendance Details"
    links:
     - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}

# Hackathon
hackathonTitle: "Hackathon"
enableHackathon: true

# Hackathon About Block
aboutHackathonTitle: "Meet our themes"
hackathonRows:
 - {title: "Android Wear", image: "hackathon-0.png", details: "The front doors will be locked because this is after hours, please park behind the building and come to the door nearest the parking lot.<br><br>Our last meeting showed that there was a lot of interest in Android Wear so we decided to put on an Android Wear Hackathon to see what you could come up with! We realize that this is pretty short notice so we hope you can help us spread the word! There will be pizza, prizes and a great group of geeks to spend the evening coding with! Even if you don't have an app idea come on in and lend a hand to someone else or maybe find inspiration once you're here!"}
 - {title: "Google Glass", image: "hackathon-1.png", details: "We love wearable computing especially Google Glass for which we want to gather the break up community in order to boost innovation.<br><br>Coding an app on Google Glass needs its Rockstar Dev : the team needs a fast learner with solid skills on Android. He knows his way around Android SDK, already checked the Glass Developement Kit (GDK) quick start guide allowing him to jump start developing an app for Glass.The Designer has the hard task to build the visual identity from the ground up, he has strong UX knowledge and a deep understanding of the new rules set by the Glass. His design skills give him the credibility to decide the most effective UI and the most compelling Glass experience."}
 - {title: "Polymer", image: "hackathon-2.png", details: "Polymer is a library that introduces web components. Web components are small elements on a page that can be extended and incorporated in web applications. The result is an increase in productivity.<br><br>We used Polymer mainly to explore the concept of web components. The transition of Google to material design was also a factor.While the library was never touched by the team, it still was painless to wireframe the application. Later on we incorporated some Polymer components in the design. We didn’t use the full potential of Polymer because of the limited time."}

# Hackathon Judges Block
judgesImage: "judges.jpg"
judgesTitle: "Judges"

# Hackathon Prizes Block
prizesTitle: "Prizes"
prizes:
 - {title: "2nd Place", image: "prize-2.png", info: "Amazing Moto 360"}
 - {title: "1nd Place", image: "prize-1.png", info: "Nexus 5 with pre-installed Android L"}
 - {title: "3nd Place", image: "prize-3.png", info: "Useful Chromecast"}

# Hackathon Location Block
hackathonLocationBlockTitle: "Location"
hackathonLocationName: "Communa"
hackathonLocationLink: "http://communa.net.ua/"
hackathonStreetAddress: "1 Halytska St"
hackathonAddressLocality: "Lviv"
hackathonAddressLocalityRegion: "Lvivska"
hackathonPostalCode: "79000"
hackathonAddressCountry: "Ukraine"
hackathonTimeTitle: "Hack through"
hackathonStartTime: "2014-10-24T10:00"
hackathonDoorTime: "09:00"
hackathonEndTime: "2014-10-25T00:00"
viewOnMap: "View on Google Maps"
hackathonPlaceCoordinates: "49.840999, 24.031144"
hackathonMapCenterCoordinates: "49.840696, 24.028754"
hackathonMapMobileCenterCoordinates: "49.841639, 24.031182"
